# Generated by Django 4.1.3 on 2022-11-05 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flower',
            name='color',
        ),
        migrations.AddField(
            model_name='flower',
            name='location',
            field=models.TextField(default='default', max_length=250),
            preserve_default=False,
        ),
    ]
