# Generated by Django 4.1.3 on 2022-11-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_flower_options_alter_garden_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='gardens',
            field=models.ManyToManyField(to='main_app.garden'),
        ),
    ]
