# Generated by Django 4.1.3 on 2022-11-11 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_flower_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250)),
                ('flower', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.flower')),
            ],
        ),
    ]
